2022-01-31 15:46:58,616 : errris comming do swagat IN PROCESS 30821 IN V-2.5.0.0
2022-01-31 15:50:04,993 : errris comming do swagat IN PROCESS 828 IN V-2.5.0.0
2022-01-31 15:51:18,908 : errris comming do swagat IN PROCESS 1345 IN V-2.5.0.0
2022-01-31 15:53:37,360 : errris comming do swagat IN PROCESS 1345 IN V-2.5.0.0
2022-01-31 15:55:55,438 : errris comming do swagat IN PROCESS 1822 IN V-2.5.0.0
2022-01-31 15:56:51,462 : errris comming do swagat IN PROCESS 2309 IN V-2.5.0.0
2022-01-31 15:57:06,645 : errris comming do swagat IN PROCESS 2309 IN V-2.5.0.0
2022-01-31 15:57:06,855 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 15:58:32,250 : errris comming do swagat IN PROCESS 2309 IN V-2.5.0.0
2022-01-31 15:58:54,114 : errris comming do swagat IN PROCESS 2309 IN V-2.5.0.0
2022-01-31 17:34:59,662 : errris comming do swagat IN PROCESS 8446 IN V-2.5.0.0
2022-01-31 17:39:57,834 : errris comming do swagat IN PROCESS 8968 IN V-2.5.0.0
2022-01-31 17:40:03,168 : errris comming do swagat IN PROCESS 8968 IN V-2.5.0.0
2022-01-31 17:40:03,632 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:16,200 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:16,202 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:16,298 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:19,155 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:19,156 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:19,199 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:20,306 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:20,307 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:20,349 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:20,678 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:20,679 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:20,721 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:21,073 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:21,073 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:21,141 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:21,288 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:21,288 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:21,333 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:40:38,897 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:38,898 : errris comming do swagat IN PROCESS 9001 IN V-2.5.0.0
2022-01-31 17:40:38,979 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:41:07,431 : errris comming do swagat IN PROCESS 9070 IN V-2.5.0.0
2022-01-31 17:41:46,544 : errris comming do swagat IN PROCESS 9070 IN V-2.5.0.0
2022-01-31 17:43:09,495 : errris comming do swagat IN PROCESS 9070 IN V-2.5.0.0
2022-01-31 17:43:09,496 : errris comming do swagat IN PROCESS 9070 IN V-2.5.0.0
2022-01-31 17:43:09,839 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:43:22,299 : errris comming do swagat IN PROCESS 9070 IN V-2.5.0.0
2022-01-31 17:43:22,311 : errris comming do swagat IN PROCESS 9070 IN V-2.5.0.0
2022-01-31 17:43:22,697 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-01-31 17:43:22,726 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-02-01 15:35:05,073 : errris comming do swagat IN PROCESS 31227 IN V-2.5.0.0
2022-02-01 15:35:05,103 : errris comming do swagat IN PROCESS 31227 IN V-2.5.0.0
2022-02-01 15:35:05,726 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-02-01 15:38:40,322 : errris comming do swagat IN PROCESS 31227 IN V-2.5.0.0
2022-02-01 15:38:40,331 : errris comming do swagat IN PROCESS 31227 IN V-2.5.0.0
2022-02-01 15:38:40,387 Internal Server Error: /listtodo/signup/
Traceback (most recent call last):
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/avis/djangular_Project/Todobackend/denvx/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-02-01 15:40:10,642 : errris comming do swagat IN PROCESS 10898 IN V-2.5.0.0
2022-02-01 15:41:18,555 : errris comming do swagat IN PROCESS 10898 IN V-2.5.0.0
2022-02-01 15:42:02,946 : errris comming do swagat IN PROCESS 10898 IN V-2.5.0.0
2022-02-01 15:48:00,024 : errris comming do swagat IN PROCESS 10898 IN V-2.5.0.0
2022-02-01 15:48:40,601 : errris comming do swagat IN PROCESS 10898 IN V-2.5.0.0
